version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing AWS CLI…"
      - pip install awscli --upgrade
      - echo "Installing Python deps into lambda-scripts/…"
      - if [ -f lambda-scripts/requirements.txt ]; then pip install -r lambda-scripts/requirements.txt -t lambda-scripts; fi

  build:
    commands:
      - echo "Packaging Lambda functions…"
      - cd lambda-scripts
      - echo "Contents of lambda-scripts:"
      - ls -la
      - zip -r ../index-photos.zip index-photos.py *.py
      - zip -r ../search-photos.zip search-photos.py *.py
      - cd ..

  post_build:
    commands:
      - echo "Deploying to Lambda…"
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://index-photos.zip
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://search-photos.zip

artifacts:
  files:
    - index-photos.zip
    - search-photos.zip
