version: 0.2

phases:
  build:
    commands:
      - echo "Packaging Lambda functions…"
      - cd lambda-scripts
      - cd index-photos
      - ls
      - zip ../../index-photos.zip lambda_function.py
      - cd ..
      - cd search-photos
      - ls
      - zip ../../search-photos.zip lambda_function.py
      - cd ..
      - cd ..

  post_build:
    commands:
      - echo "Deploying to Lambda…"
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://index-photos.zip
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://search-photos.zip

artifacts:
  files:
    - index-photos.zip
    - search-photos.zip
