version: 0.2

phases:
  build:
    commands:
      - echo "Packaging Lambda functions…"
      - cd lambda-scripts
      - echo "Contents of lambda-scripts:"
      - ls -la
      - zip -r ../index-photos.zip index-photos.py
      - zip -r ../search-photos.zip search-photos.py
      - cd ..

  post_build:
    commands:
      - echo "Deploying to Lambda…"
      - aws lambda update-function-code --function-name index-photos/lambda_function --zip-file fileb://index-photos.zip
      - aws lambda update-function-code --function-name search-photos/lambda_function --zip-file fileb://search-photos.zip

artifacts:
  files:
    - index-photos.zip
    - search-photos.zip
