version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.13  # Changed to 3.12 since Lambda does not support 3.13
    commands:
      - pip install awscli
  build:
    commands:
      - echo "Packaging Lambda functions..."
      - echo "Current directory: $(pwd)"
      - echo "Listing files in the root directory:"
      - ls -la
      - echo "Changing to lambda-scripts directory..."
      - cd lambda-scripts || echo "Failed to change to lambda-scripts directory"
      - echo "Current directory: $(pwd)"
      - echo "Listing files in lambda-scripts directory:"
      - ls -la
      - zip -r ../index-photos.zip index-photos.py
      - zip -r ../search-photos.zip search-photos.py
      - cd ..
  post_build:
    commands:
      - echo "Deploying to Lambda..."
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://index-photos.zip
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://search-photos.zip
artifacts:
  files:
    - index-photos.zip
    - search-photos.zip
